'use strict'
// новые базы данных : Массивы Объектов : вкуснотищща
const KESS = {
    player: 'Vadimka',
    isGM: false,
    charShortName: 'Кэсс', charLongName: 'Кассандра Стараг',
    charShortConcept: 'ведьма призыва', charLongDescr: 'ведьма-призыватель',
    bkgImage: './img/kess_bg.png',
    maxHP: 36, currentHP: 36,
    initD6: 3, initMod: 1,
    maxActionPoints: 12, currentRoundAP: 12,
    speedFt: 24, speedHx: 5, runMult: 5,
    armor:   [],
    attack:  [
        { shortName:'Волшебная палочка МР', longName:'Волшебная палочка МР', meel:false, complex:true,
            actionPoints:5, reload:false,
        	attackDice:2, attackMod:3, damageDice:4, damageMod:0,
            wParts: [{ attackName:'Энтропия', ammunition:13, },],
            criticalChance:99, criticalDamage:5, armorPiercing:0, knockingDown:0,
            range:2, parry:7, weight:0.2, price:'?', coins:'gp', hardness:5, condition:2, },

		{ shortName:'Гоблинский жезл МР', longName:'Гоблинский жезл МР', meel:false, complex:true,
            actionPoints:5, reload:false,
        	attackDice:'auto', damageDice:4, damageMod:4,
            wParts: [{ attackName:'Волшебная стрела', ammunition:14, },],
            criticalChance:99, criticalDamage:5, armorPiercing:0, knockingDown:0,
            range:96, parry:7, weight:1.5, price:'?', coins:'gp', hardness:6, condition:9, },

		{ shortName:'Заклинание', longName:'Кэсс, заклинание', meel:false, complex:true,
            actionPoints:10, reload:false,
        	attackDice:2, attackMod:3, damageDice:5, damageMod:2,
            wParts: [
                { attackName:'Анимирование, 1 круг', actionPoints:8,},
                { attackName:'Заклинание, 1 круг', actionPoints:10,},
                { attackName:'Чары, Воплощ, 1 круг', actionPoints:12,},
                { attackName:'Анимирование, 2 круг', actionPoints:16,},
                { attackName:'Заклинание, 2 круг', actionPoints:20,},
                { attackName:'Чары, Воплощ, 2 круг', actionPoints:24,},
                { attackName:'Анимирование, 3 круг', actionPoints:24,},
                { attackName:'Заклинание, 3 круг', actionPoints:30,},
                { attackName:'Чары, Воплощ, 3 круг', actionPoints:36,},
                { attackName:'Анимирование, 4 круг', actionPoints:32,},
                { attackName:'Заклинание, 4 круг', actionPoints:40,},
                { attackName:'Чары, Воплощ, 4 круг', actionPoints:48,},
                { attackName:'Анимирование, 5 круг', actionPoints:40,},
                { attackName:'Заклинание, 5 круг', actionPoints:50,},
                { attackName:'Чары, Воплощ, 5 круг', actionPoints:60,},
            ],
            criticalChance:99, criticalDamage:5, armorPiercing:0, knockingDown:0,
            range:2, parry:7, weight:0, price:0, coins:'gp', hardness:0, condition:0, },

        { shortName:'Кинжал МР', longName:'Метеоритовый кинжал МР', meel:true, complex: false,
            actionPoints:3,
        	attackName:'Колоть', attackDice:3, attackMod:2, damageDice:3, damageMod:2,
        	criticalChance:9, criticalDamage:5, armorPiercing:1, knockingDown:0,
            range:1, parry:10, weight:0.5, price:6, coins:'gp', hardness:12, condition:6, },
    ],
    defence: [
		{ shortName:'Париро&shyвание', longName:'Кинжал, парирование', actionPoints:2, parry:10, },
		{ shortName:'Уклоне&shyние',   longName:'Кэсс, уклонение',     actionPoints:2, parry:13, },
	],
};
