'use strict'
// новые базы данных : Массивы Объектов : вкуснотищща
const LONA = {
    player: 'Vsevyd',
    isGM: false,
    charShortName: 'Лона', charLongName: 'Лориена "Тёмная Звезда"',
    charShortConcept: 'жрица и бард', charLongDescr: 'жрица и бард',
    bkgImage: './img/lona_bg.png',
    maxHP: 20, currentHP: 20,
    initD6: 3, initMod: 1,
    maxActionPoints: 14, currentRoundAP: 14,
    speedFt: 32, speedHx: 6, runMult: 5,
    armor:   [],
    attack:  [
        { shortName:'Посож Жрицы', longName:'Посох жрицы Сеханин, ХР', meel:false, complex:true,
            actionPoints:5, reload:false,
            attackDice:2, attackMod:1, damageDice:4, damageMod:0,
            wParts: [
                { attackName:'Чары, 1 круг', actionPoints:8, attackDice:2, attackMod:2, damageDice:5, damageMod:0,},
                { attackName:'Заклинание, 1 круг', actionPoints:10, attackDice:2, attackMod:2, damageDice:5, damageMod:0,},
                { attackName:'Прориц, Аним, 1 круг', actionPoints:12, attackDice:2, attackMod:2, damageDice:5, damageMod:0,},
                { attackName:'Чары, 2 круг', actionPoints:16, attackDice:2, attackMod:2, damageDice:5, damageMod:0,},
                { attackName:'Заклинание, 2 круг', actionPoints:20, attackDice:2, attackMod:2, damageDice:5, damageMod:0,},
                { attackName:'Прориц, Аним, 2 круг', actionPoints:24, attackDice:2, attackMod:2, damageDice:5, damageMod:0,},
                { attackName:'Чары, 3 круг', actionPoints:24, attackDice:2, attackMod:2, damageDice:5, damageMod:0,},
                { attackName:'Заклинание, 3 круг', actionPoints:30, attackDice:2, attackMod:2, damageDice:5, damageMod:0,},
                { attackName:'Прориц, Аним, 3 круг', actionPoints:36, attackDice:2, attackMod:2, damageDice:5, damageMod:0,},
                { attackName:'Чары, 4 круг', actionPoints:32, attackDice:2, attackMod:2, damageDice:5, damageMod:0,},
                { attackName:'Заклинание, 4 круг', actionPoints:40, attackDice:2, attackMod:2, damageDice:5, damageMod:0,},
                { attackName:'Прориц, Аним, 4 круг', actionPoints:48, attackDice:2, attackMod:2, damageDice:5, damageMod:0,},
                { attackName:'Чары, 5 круг', actionPoints:40, attackDice:2, attackMod:2, damageDice:5, damageMod:0,},
                { attackName:'Заклинание, 5 круг', actionPoints:50, attackDice:2, attackMod:2, damageDice:5, damageMod:0,},
                { attackName:'Прориц, Аним, 5 круг', actionPoints:60, attackDice:2, attackMod:2, damageDice:5, damageMod:0,},
                { attackName:'Стукнуть', },
            ],
            criticalChance:99, criticalDamage:5, armorPiercing:0, knockingDown:5,
            range:2, parry:10,
            weight:3, price:15, coins:'sp', hardness:6, condition:18, },

		{ shortName:'Шпага МР', longName:'Шпага МР', meel:true, complex:true,
            pair:true, mainHand:true, attackPenalty:2,
            actionPoints:5, attackDice:4, attackMod:3, damageDice:4, damageMod:3,
            wParts: [
                { attackName:'Колоть', armorPiercing:2, knockingDown:0, },
                { attackName:'Pубить', armorPiercing:0, knockingDown:2, },
                { attackName:'Удар', actionPoints:3, attackDice:4, attackMod:0, damageDice:3, damageMod:0, armorPiercing:0, knockingDown:4, },
            ],
            enchantments: [
                { enchName:'Волшебное оружие', duration:'fight', amount:32, attackDice:1, damageDice:1, },
            ],
        	criticalChance:9, criticalDamage:5,
            range:4,  parry:18,
            weight:2.5, price:24, coins:'gp', hardness:11, condition:28, },
		{ shortName:'Дага MP', longName:'Дага MP', meel:true, complex:true,
            pair:true, mainHand:false, attackPenalty:2, actionPoints:3,
            attackDice:3, attackMod:1, damageDice:3, damageMod:1,
            wParts: [
                { attackName:'Колоть', armorPiercing:2, knockingDown:-2, },
                { attackName:'Удар', actionPoints:3, damageDice:3, damageMod:0, armorPiercing:0, knockingDown:4, },
            ],
        	criticalChance:9, criticalDamage:6,
            range:1, parry:15,
            weight:0.6, price:9, coins:'sp', hardness:11, condition:6,},
        { shortName:'Боевая плеть', longName:'Боевая плеть', meel:true,
            actionPoints:6,
            attackName:'Удар', attackDice:3, attackMod:2, damageDice:4, damageMod:2,
            criticalChance:9, criticalDamage:5, armorPiercing:0, knockingDown:5,
            range:10, parry:14,
            weight:2.5, price:3, coins:'sp', hardness:3, condition:7, },
        { shortName:'Лук', longName:'Короткий составной эльфийский лук', meel:false, complex:true,
            actionPoints:6, reload:3,
            attackDice:4,   attackMod:1,
            wParts: [{ attackName:'Боевая стрела', ammunition:17, damageDice:7, damageMod:1, armorPiercing:2, knockingDown:0,},],
            criticalChance:9, criticalDamage:5,
            range:5,
            weight:3, price:22, coins:'sp', hardness:8, condition:22, },
            ],
    defence: [
		{ shortName:'Шпага', longName:'Шпага, парирование', actionPoints:4,
            parry:18,        },
		{ shortName:'Дага', longName:'Дага, парирование', actionPoints:2,
            parry:15,        },
		{ shortName:'Уворот', longName:'Уклонение', actionPoints:2,
            parry:14,        },
		{ shortName:'Плащ', longName:'Защита плащом', actionPoints:2,
            parry:18,        },
	],
};
