'use strict'
// новые базы данных : Массивы Объектов : вкуснотищща
const LOTA = {
    player: 'Tamara',
    isGM: false,
    charShortName: 'Лота', charLongName: 'Лотанария Солнецный Цветок',
    charShortConcept: 'травница', charLongDescr: 'травница-чародейка',
    bkgImage: './img/lota_bg.png',
    maxHP: 16, currentHP: 16,
    initD6: 3, initMod: 1,
    maxActionPoints: 12, currentRoundAP: 12,
    speedFt: 33, speedHx: 7, runMult: 5,
    armor:   [],
    attack:  [
        { shortName:'Cабля', longName:'Отцовская сабля', meel:true, complex:false,
            actionPoints:4,
        	attackName:'Pубить', attackDice:3, attackMod:2, damageDice:6, damageMod:2,
        	criticalChance:10, criticalDamage:5, armorPiercing:0, knockingDown:2,
            range:4, parry:14, weight:3, price:10, coins:'sp', hardness:10, condition:30,},
        { shortName:'Скальпель МР', longName:'Скальпель МР', meel:true, complex: false,
            actionPoints:3,
        	attackName:'Колоть', attackDice:4, attackMod:2, damageDice:3, damageMod:1,
        	criticalChance:10, criticalDamage:5, armorPiercing:0, knockingDown:-1,
            range:0, parry:13, weight:0.2, price:3, coins:'sp', hardness:11, condition:3,},
		{ shortName:'Шар магический', longName:'Шар из Среброкорника МР', meel:false, complex:true,
            actionPoints:5, reload:false,
        	attackDice:2, attackMod:2, damageDice:4, damageMod:2,
            wParts: [{ attackName:'Свет', },
                     { attackName:'Вода', },
                     { attackName:'Земля', damageDice:3, damageMod:1, },
            ],
            criticalChance:10, criticalDamage:5, armorPiercing:0, knockingDown:0,
            range:2, parry:8, weight:1, price:75, coins:'sp', hardness:4, condition:6,},
        ],
    defence: [
		{ shortName:'Cабля', longName:'Cабля, парирование', actionPoints:3, parry:14,},
		{ shortName:'Скальпель', longName:'Скальпель, парирование', actionPoints:2, parry:13,},
		{ shortName:'Уклоне&shyние',   longName:'Лота, уклонение',     actionPoints:2, parry:13,},
		{ shortName:'Заклина&shyние',   longName:'Заклинание щит',     actionPoints:5, parry:16,},
	],
};
