'use strict'
// новые базы данных : Массивы Объектов : вкуснотищща
const SKELETON = { // Skeleton
    player: 'GM',
    isGM: true,
    charShortName: 'Скелет', charLongName: 'Скелет опытного воина',
    charShortConcept: '', charLongDescr: '',
    bkgImage: './img/skeleton.jpg',
    maxHP: 32, currentHP: 32,
    initD6: 3, initMod: 0,
    maxActionPoints: 14, currentRoundAP: 14,
    speedFt: 30, speedHx: 6, runMult: 5,
    armor:   [],
    attack:  [
        		{ shortName:'Короткое копьё', longName:'Короткое копьё', meel:true, complex:false,actionPoints:5,
                	attackName:'Колоть', attackDice:4, attackMod:1, damageDice:5, damageMod:1,
                	criticalChance:10, criticalDamage:7, armorPiercing:2, knockingDown:0,
                    range:8, parry:17, weight:2, price:2, coins:'sp', condition:5, conditionMax:10,},
                { shortName:'Тяжелая булава', longName:'Тяжелая булава', meel:true, complex:false,actionPoints:6,
                    attackName:'Бить', attackDice:4, attackMod:1, damageDice:5, damageMod:1,
                    criticalChance:10, criticalDamage:7, armorPiercing:0, knockingDown:4,
                    range:3, parry:17, weight:2, price:3, coins:'sp', condition:5, conditionMax:10,},
                { shortName:'Укус', longName:'Скелет, укус', meel:true, complex:false,actionPoints:4,
                	attackName:'Рвать', attackDice:4, attackMod:0, damageDice:4, damageMod:3,
                    criticalChance:10, criticalDamage:7, armorPiercing:0, knockingDown:4,
                    range:0, parry:16, weight:0, price:0, coins:'sp', condition:0, conditionMax:0,},
                { shortName:'Когти', longName:'Скелет, когти', meel:true, complex:false,actionPoints:3,
                    attackName:'Рвать', attackDice:4, attackMod:1, damageDice:3, damageMod:2,
                    criticalChance:10, criticalDamage:7, armorPiercing:0, knockingDown:2,
                    range:0, parry:16, weight:0, price:0, coins:'sp', condition:0, conditionMax:0,},
                {shortName:'Сулица', longName:'Бросок сулицы', meel:false, complex:false, actionPoints:5, reload:1,
                    attackName:'Метать', ammunition:6,
                    attackDice:4, attackMod:0, damageDice:5, damageMod:0,
                    criticalChance:10, criticalDamage:7, armorPiercing:0, knockingDown:4,
                    range:2, parry:17, weight:2, price:2, coins:'sp', condition:5, conditionMax:10,},
            ],
    defence: [
        		{ shortName:'Блок', longName:'Скелет, блок щитом', actionPoints:3, parry:20,},
        		{ shortName:'Уклонение',   longName:'Скелет, уклонение', actionPoints:2, parry:16,},
	],
};
const ZOMBIE = { // Zombie
    player: 'GM',
    isGM: true,
    charShortName: 'Зомби', charLongName: 'Зомби опытного воина',
    charShortConcept: '', charLongDescr: '',
    bkgImage: './img/zombie.jpg',
    maxHP: 48, currentHP: 48,
    initD6: 3, initMod: 0,
    maxActionPoints: 10, currentRoundAP: 10,
    speedFt: 25, speedHx: 5, runMult: 4,
    armor:   [],
    attack:  [
		{ shortName:'Короткое копьё', longName:'Короткое копьё', meel:true, complex:false, actionPoints:5,
        	attackName:'Колоть', attackDice:3, attackMod:2, damageDice:5, damageMod:2,
        	criticalChance:10, criticalDamage:7, armorPiercing:2, knockingDown:0,
            range:8, parry:14, weight:2, price:2, coins:'sp', condition:5, conditionMax:10,},
        { shortName:'Тяжелая булава', longName:'Тяжелая булава', meel:true, complex:false, actionPoints:6,
            attackName:'Бить', attackDice:3, attackMod:2, damageDice:5, damageMod:2,
            criticalChance:10, criticalDamage:7, armorPiercing:0, knockingDown:4,
            range:3, parry:14, weight:2, price:3, coins:'sp', condition:5, conditionMax:10,},
        { shortName:'Укус', longName:'Зомби, укус', meel:true, complex:false, actionPoints:4,
        	attackName:'Рвать', attackDice:3, attackMod:1, damageDice:5, damageMod:0,
            criticalChance:10, criticalDamage:7, armorPiercing:0, knockingDown:4,
            range:0, parry:13, weight:0, price:0, coins:'sp', condition:0, conditionMax:0,},
        { shortName:'Когти', longName:'Зомби, когти', meel:true, complex:false, actionPoints:3,
            attackName:'Рвать', attackDice:3, attackMod:2, damageDice:4, damageMod:0,
            criticalChance:10, criticalDamage:7, armorPiercing:0, knockingDown:2,
            range:0, parry:13, weight:0, price:0, coins:'sp', condition:0, conditionMax:0,},
        {shortName:'Сулица', longName:'Бросок сулицы', meel:false, complex:false, actionPoints:5, reload:1,
            attackName:'Метнуть', ammunition:6,
            attackDice:3, attackMod:1, damageDice:5, damageMod:1,
            criticalChance:10, criticalDamage:7, armorPiercing:0, knockingDown:4,
            range:2, parry:14, weight:2, price:2, coins:'sp', condition:5, conditionMax:10,},
            ],
    defence: [
		{ shortName:'Блок', longName:'Зомби, блок щитом', actionPoints:3, parry:17,},
		{ shortName:'Уклонение', longName:'Зомби, уклонение', actionPoints:2, parry:13,},
	],
};
